# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import Estate
import login
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1003, 945)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.My_sobs_table = QtWidgets.QTableWidget(self.tab)
        self.My_sobs_table.setObjectName("My_sobs_table")
        self.My_sobs_table.setColumnCount(0)
        self.My_sobs_table.setRowCount(0)
        self.My_sobs_table.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.My_sobs_table)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.update_push_button_1 = QtWidgets.QPushButton(self.tab)
        self.update_push_button_1.setObjectName("update_push_button_1")
        self.verticalLayout_3.addWidget(self.update_push_button_1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.Ptesents_table_1 = QtWidgets.QTableWidget(self.tab_2)
        self.Ptesents_table_1.setObjectName("Ptesents_table_1")
        self.Ptesents_table_1.setColumnCount(0)
        self.Ptesents_table_1.setRowCount(0)
        self.verticalLayout_4.addWidget(self.Ptesents_table_1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.Presen_push_button = QtWidgets.QPushButton(self.tab_2)
        self.Presen_push_button.setObjectName("Presen_push_button")
        self.gridLayout.addWidget(self.Presen_push_button, 1, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.chansel_present_push_button = QtWidgets.QPushButton(self.tab_2)
        self.chansel_present_push_button.setObjectName("chansel_present_push_button")
        self.gridLayout_2.addWidget(self.chansel_present_push_button, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.tableWidget_14 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_14.setObjectName("tableWidget_14")
        self.tableWidget_14.setColumnCount(0)
        self.tableWidget_14.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_14)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_3.addWidget(self.pushButton_20, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_9.addWidget(self.pushButton_2)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.gridLayout_4.addLayout(self.verticalLayout_30, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_12.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableWidget_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_7.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableWidget_5)
        self.gridLayout_9.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_14.addWidget(self.lineEdit_3)
        self.gridLayout_8.addLayout(self.verticalLayout_14, 0, 1, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_15.addWidget(self.label_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_15.addWidget(self.lineEdit_2)
        self.gridLayout_8.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_8.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_9)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.verticalLayout_16.addWidget(self.tableWidget_6)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_10.addWidget(self.pushButton_7, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 0, 0, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_17.addWidget(self.label_12)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.verticalLayout_17.addWidget(self.tableWidget_7)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_6.addWidget(self.pushButton_8, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 0, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_17)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_11.addWidget(self.pushButton_9, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 0, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_11)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.verticalLayout_18.addWidget(self.tableWidget_4)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_20.addWidget(self.label_14)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_20.addWidget(self.lineEdit_5)
        self.gridLayout_12.addLayout(self.verticalLayout_20, 0, 1, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_19.addWidget(self.label_13)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_19.addWidget(self.lineEdit_4)
        self.gridLayout_12.addLayout(self.verticalLayout_19, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_12.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_12)
        self.verticalLayout_24.addLayout(self.verticalLayout_18)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.verticalLayout_21.addWidget(self.tableWidget_8)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_13.addWidget(self.pushButton_10, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem10, 0, 0, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout_13)
        self.verticalLayout_24.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_22.addWidget(self.label_16)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.verticalLayout_22.addWidget(self.tableWidget_9)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_14.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_14.addWidget(self.pushButton_11, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem11, 0, 0, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_14)
        self.verticalLayout_24.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_23.addWidget(self.label_17)
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(0)
        self.tableWidget_10.setRowCount(0)
        self.verticalLayout_23.addWidget(self.tableWidget_10)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem12, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_15.addWidget(self.pushButton_14, 0, 1, 1, 1)
        self.verticalLayout_23.addLayout(self.gridLayout_15)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_16.addWidget(self.pushButton_13, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem13, 0, 0, 1, 1)
        self.verticalLayout_24.addLayout(self.gridLayout_16)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_25.addWidget(self.label_18)
        self.tableWidget_11 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(0)
        self.tableWidget_11.setRowCount(0)
        self.verticalLayout_25.addWidget(self.tableWidget_11)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_17.addWidget(self.pushButton_15, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem14, 0, 0, 1, 1)
        self.verticalLayout_25.addLayout(self.gridLayout_17)
        self.verticalLayout_28.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_26.addWidget(self.label_19)
        self.tableWidget_12 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(0)
        self.tableWidget_12.setRowCount(0)
        self.verticalLayout_26.addWidget(self.tableWidget_12)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_18.addWidget(self.pushButton_16, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem15, 0, 0, 1, 1)
        self.verticalLayout_26.addLayout(self.gridLayout_18)
        self.verticalLayout_28.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_27.addWidget(self.label_20)
        self.tableWidget_13 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.setColumnCount(0)
        self.tableWidget_13.setRowCount(0)
        self.verticalLayout_27.addWidget(self.tableWidget_13)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_19.addWidget(self.pushButton_17, 0, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem16, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_19.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout_19)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_20.addWidget(self.pushButton_19, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem17, 0, 0, 1, 1)
        self.verticalLayout_28.addLayout(self.gridLayout_20)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.widget = QtWidgets.QWidget(self.tab_7)
        self.widget.setGeometry(QtCore.QRect(380, 330, 137, 213))
        self.widget.setObjectName("widget")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_36.addWidget(self.label_24)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_36.addWidget(self.lineEdit_8)
        self.verticalLayout_37.addLayout(self.verticalLayout_36)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_33.addWidget(self.label_25)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_33.addWidget(self.lineEdit_9)
        self.verticalLayout_37.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_34.addWidget(self.label_26)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_34.addWidget(self.lineEdit_10)
        self.verticalLayout_37.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_35.addWidget(self.label_27)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_35.addWidget(self.lineEdit_11)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_35.addWidget(self.pushButton_21)
        self.verticalLayout_37.addLayout(self.verticalLayout_35)
        self.tabWidget.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Код начинается отсюда
        #Основные Переменные
        self.out_pass_file = open("pass.txt", "r")
        self.out_login_file = open("login.txt", "r")
        self.Main_Login = self.out_login_file.readlines()
        self.Main_Password = self.out_pass_file.readlines()
        self.STATION = None
        if self.Main_Login[0] == "0xAc771378BB6c2b8878fbF75F80880cbdDefd1B1e" and self.Main_Password[0]=="123456789":
            self.STATION=True
        else:
            self.STATION = False
        if self.STATION==True:
            print("Welcom Aministrator")
        else:
            self.lineEdit_8.setDisabled(True)
            self.lineEdit_9.setDisabled(True)
            self.lineEdit_10.setDisabled(True)
            self.lineEdit_11.setDisabled(True)
            self.pushButton_21.setDisabled(True)
        self.present_time = 0
        self.present_addres = 0
        #Основные Переменные

        self.out_pass_file.close()
        self.out_login_file.close()
        print("Login", self.Main_Login) # DEBUG
        print("Password", self.Main_Password) # DEBUG
        #ИНИЦИАЛИЗАЦИЯ ТАБЛИЦ
        self.My_sobs_table.setRowCount(7)# Строки
        self.My_sobs_table.setColumnCount(7) #Столбцы
        self.Ptesents_table_1.setRowCount(5)
        self.Ptesents_table_1.setColumnCount(4)
        self.Ptesents_table_1.setHorizontalHeaderLabels(["Id","Адрес собственности","Площадь","Полезная площадь"])
        self.My_sobs_table.setHorizontalHeaderLabels(["Id","Адрес собственности","Общая площадь","Полезная площадь","Подарок","Продажа","Залог"])
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(7)
        self.tableWidget.setHorizontalHeaderLabels(["Id","Для кого","Адрес","Площадь","Полезная Площадь","Срок"])
        self.tableWidget_5.setColumnCount(4)
        self.tableWidget_5.setRowCount(7)
        self.tableWidget_5.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная Площадь"])
        self.tableWidget_6.setColumnCount(6)
        self.tableWidget_6.setRowCount(7)
        self.tableWidget_6.setHorizontalHeaderLabels(["Id","Ифнормация","Площадь","Полезная площадь","Цена","Срок"])
        self.tableWidget_7.setColumnCount(8)
        self.tableWidget_7.setRowCount(7)
        self.tableWidget_7.setHorizontalHeaderLabels(["Id","Ифнормация","Площадь","Полезная площадь","Наменальная цена","Срок","Покупатель","Предложенная цена"])
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(7)
        self.tableWidget_2.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Цена","Срок"])
        self.tableWidget_3.setColumnCount(8)
        self.tableWidget_3.setRowCount(7)
        self.tableWidget_3.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Наминальная цена","Срок","Покупатель","Предложенная цена"])
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(7)
        self.tableWidget_4.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь"])
        self.tableWidget_8.setColumnCount(6)
        self.tableWidget_8.setRowCount(7)
        self.tableWidget_8.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Деньги","Длительность"])
        self.tableWidget_9.setColumnCount(7)
        self.tableWidget_9.setRowCount(7)
        self.tableWidget_9.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Предлогает залог","Деньги","Длительность"])
        self.tableWidget_10.setColumnCount(7)
        self.tableWidget_10.setRowCount(7)
        self.tableWidget_10.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Залогодатель", "Сумма","Срок"])
        self.tableWidget_11.setRowCount(7)
        self.tableWidget_11.setColumnCount(7)
        self.tableWidget_11.setHorizontalHeaderLabels(["Id","Кому выдать","Площадь","Полезная площадь","Информация","Сумма" ,"Длительность"])
        self.tableWidget_12.setRowCount(7)
        self.tableWidget_12.setColumnCount(7)
        self.tableWidget_12.setHorizontalHeaderLabels(["Id","Кому выдать","Площадь","Полезная площадь","Информация","Сумма" ,"Длительность"])
        self.tableWidget_13.setColumnCount(7)
        self.tableWidget_13.setRowCount(7)
        self.tableWidget_13.setHorizontalHeaderLabels(["Id", "Информация", "Площадь", "Полезная площадь", "Залогодатель", "Сумма", "Срок"])
        self.tableWidget_14.setColumnCount(6)
        self.tableWidget_14.setRowCount(7)
        self.tableWidget_14.setHorizontalHeaderLabels(["Id","От кого","Информация","Площадь","Полезная площадь","Срок"])
        #КОНЕЦ ИНИЦИАЛИЗАЦИЙ ТАБЛИЦ
        #МАТРИЦЫ
        self.Matrix_For_My_sobs_table = [[]]
        self.Matrix_For_Presents = [[]]
        self.Matrix_For_Mine_Presents = [[]]
        self.Matrix_For_Can_Be_Slea = [[]]
        self.Matix_For_My_Sales = [[]]
        self.Matrix_For_Who_Wont_To_By = [[]]
        self.Matrix_For_Choose_to_by = [[]]
        self.Matrix_For_I_By =[[]]
        self.Matrix_For_Zalog_My_Sobstvennost = [[]]
        self.Matrix_For_My_Zalogs = [[]]
        self.Matrix_For_Get_Zalog = [[]]
        self.Matrix_For_Getting_For_Me_Zalogs = [[]]
        self.Matrix_For_Gettin_Other_Zalog =[[]]
        self.Matrix_For_Pred_My_Zalogs =[[]]
        self.Matrix_For_Get_My_Zalogs =[[]]
        self.Matrix_For_My_Presents = [[]]
        #КОНЕЦ МАТРИЦ

        #СИГНАЛЫ
        self.update_push_button_1.clicked.connect(self.get_my_estates)
        self.pushButton.clicked.connect(self.get_can_my_presents)
        self.Presen_push_button.clicked.connect(self.create_present)
        self.pushButton_9.clicked.connect(self.udpate_tables_slae)
        self.pushButton_5.clicked.connect(self.update_table_choose)
        self.pushButton_13.clicked.connect(self.zalog_update)
        self.pushButton_19.clicked.connect(self.update_get_zalog)
        self.pushButton_2.clicked.connect(self.take_by)
        self.pushButton_6.clicked.connect(self.create_sole_slot)
        self.chansel_present_push_button.clicked.connect(self.chansle_1)
        self.pushButton_4.clicked.connect(self.create_playedge_slot)
        self.pushButton_21.clicked.connect(self.Admin_Slot)

        #КОНЕЦ СИГНАЛОВ
        self.Estate_main_object = Estate.Estate()
        Station = self.Estate_main_object.auth(self.Main_Login[0], self.Main_Password[0])
        print("Login Station", Station)  # DEBUG

    def Admin_Slot(self):
        self.userAdrr = self.lineEdit_8.text()
        self.FisicAddress = self.lineEdit_9.text()
        self.Square = self.lineEdit_10.text()
        self.UsefulSquare = self.lineEdit_11.text()
        self.Estate_main_object.create_estate(self.userAdrr,self.FisicAddress,self.Square,self.UsefulSquare)

    def get_my_estates(self):
       self.My_sobs_table.clear()
       self.My_sobs_table.setHorizontalHeaderLabels(
           ["Id", "Адрес собственности", "Общая площадь", "Полезная площадь", "Подарок", "Продажа", "Залог"])
       self.Matrix_For_My_sobs_table = self.Estate_main_object.my_estates()
       if self.Matrix_For_My_sobs_table == []:
           print("Matrix_For_My_sobs_table is emty ")
       else:
           print(self.Matrix_For_My_sobs_table)  # DEBUG
           self.My_sobs_table.setRowCount(len(self.Matrix_For_My_sobs_table))  # Количество столбцов
           self.My_sobs_table.setColumnCount(len(self.Matrix_For_My_sobs_table[0]))  # Количество строк

           for i in range(len(self.Matrix_For_My_sobs_table)):
               for j in range(len(self.Matrix_For_My_sobs_table[0])):
                   self.My_sobs_table.setItem(i, j, QTableWidgetItem(self.Matrix_For_My_sobs_table[i][j]))

    def get_can_my_presents(self):
        self.Ptesents_table_1.clear()
        self.Ptesents_table_1.setHorizontalHeaderLabels(
            ["id", "Адрес собственности", "Площадь", "Полезная площадь"])
        self.Matrix_For_Presents = self.Estate_main_object.can_present()
        if self.Matrix_For_Presents == []:
            print("Matrix For Presents Is Emty")
        else:
            print(self.Matrix_For_Presents)  # DEBUG
            self.Ptesents_table_1.setRowCount(len(self.Matrix_For_Presents))
            self.Ptesents_table_1.setColumnCount(len(self.Matrix_For_Presents[0]))

            for i in range(len(self.Matrix_For_Presents)):
                for j in range(len(self.Matrix_For_Presents[0])):
                    self.Ptesents_table_1.setItem(i, j, QTableWidgetItem(self.Matrix_For_Presents[i][j]))
        self.tableWidget.clear()
        self.tableWidget.setHorizontalHeaderLabels(["Id", "Для кого", "Адрес", "Площадь", "Полезная Площадь", "Срок"])
        self.Matrix_For_Mine_Presents = self.Estate_main_object.i_presented()
        if self.Matrix_For_Mine_Presents == []:
            print("Matrix For Mine Presents Is Emty")
        else:
            print(self.Matrix_For_Mine_Presents)#DEBUG
            self.tableWidget.setRowCount(len(self.Matrix_For_Mine_Presents))
            self.tableWidget.setColumnCount(len(self.Matrix_For_Mine_Presents[0]))

            for i in range (len(self.Matrix_For_Mine_Presents)):
                for j in range(len(self.Matrix_For_Mine_Presents[0])):
                    self.tableWidget.setItem(i,j,QTableWidgetItem(self.Matrix_For_Mine_Presents[i][j]))
        self.tableWidget_14.clear()
        self.tableWidget_14.setHorizontalHeaderLabels(["Id","От кого","Информация","Площадь","Полезная площадь","Срок"])
        self.Matrix_For_My_Presents = self.Estate_main_object.my_present()
        if self.Matrix_For_My_Presents == []:
            print("Matrix_For_My_Presents Is Emty") #DEBUG
        else:
            print(self.Matrix_For_My_Presents)  # DEBUG
            self.tableWidget_14.setRowCount(len(self.Matrix_For_My_Presents))
            self.tableWidget_14.setColumnCount(len(self.Matrix_For_My_Presents[0]))

            for i in range(len(self.Matrix_For_My_Presents)):
                for j in range(len(self.Matrix_For_My_Presents[0])):
                    self.tableWidget_14.setItem(i, j, QTableWidgetItem(self.Matrix_For_My_Presents[i][j]))
    def create_sole_slot(self):
        Row = self.tableWidget_5.currentRow()
        estate_id = self.tableWidget_5.item(Row,0).text()
        print(estate_id) #DEBUG
        Time = self.lineEdit_3.text()
        Price = self.lineEdit_2.text()
        self.Estate_main_object.create_sale(estate_id,Price,Time)

    def create_present(self):
        #estate_id = self.Ptesents_table_1.currentItem().text()
        ROW = self.Ptesents_table_1.currentRow()
        print(ROW)
        estate_id = self.Ptesents_table_1.item(ROW,0).text()
        print(estate_id)#DEBUG
        #print(estate_id)#DEBUG
        self.present_addres=self.lineEdit_6.text()
        self.present_time = self.lineEdit_7.text()
        self.Estate_main_object.create_present(estate_id ,self.present_addres,self.present_time)
    def chansle_1(self):
        Row = self.tableWidget.currentRow()
        estate_id = self.tableWidget.item(Row, 0).text()
        print(estate_id)  # DEBUG
        self.Estate_main_object.cancel_present(estate_id)

    def take_by(self):
        Row = self.tableWidget.currentRow()
        estate_id = self.tableWidget.item(Row, 0).text()
        print(estate_id)  # DEBUG
        Price  = self.lineEdit.text()
        self.Estate_main_object.i_want_to_buy(estate_id,Price)
    def create_playedge_slot(self):
        Row = self.tableWidget_4.currentRow()
        estate_id = self.tableWidget_4.item(Row, 0).text()
        print(estate_id)  # DEBUG
        Price = self.lineEdit_4.text()
        Days = self.lineEdit_5.text()
        self.Estate_main_object.create_pledge(estate_id,Price,Days)



    def udpate_tables_slae(self):
        self.tableWidget_5.clear()
        self.tableWidget_5.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная Площадь"])
        self.Matrix_For_Can_Be_Slea = self.Estate_main_object.can_sale()
        print("Таблица   ",self.Matrix_For_Can_Be_Slea)
        if self.Matrix_For_Can_Be_Slea == []:
            print("Matrix_For_Cam_Be_Slea is Emty")
        else:
            self.tableWidget_5.setRowCount(len(self.Matrix_For_Can_Be_Slea))
            self.tableWidget_5.setColumnCount(len(self.Matrix_For_Can_Be_Slea[0]))
            for i in range(len(self.Matrix_For_Can_Be_Slea)):
                for j in range(len(self.Matrix_For_Can_Be_Slea[0])):
                    self.tableWidget_5.setItem(i,j,QTableWidgetItem(self.Matrix_For_Can_Be_Slea[i][j]))
        self.tableWidget_6.clear()
        self.tableWidget_6.setHorizontalHeaderLabels(["Id","Ифнормация","Площадь","Полезная площадь","Цена","Срок"])
        self.Matix_For_My_Sales = self.Estate_main_object.my_sales()
        if self.Matix_For_My_Sales == []:
            print("Matix_For_My_Sales is Emty")
        else:
            self.tableWidget_6.setRowCount(len(self.Matix_For_My_Sales))
            self.tableWidget_6.setColumnCount(len(self.Matix_For_My_Sales[0]))

            for i in range(len(self.Matix_For_My_Sales)):
                for j in range(len(self.Matix_For_My_Sales[0])):
                    self.tableWidget_6.setItem(i,j,QTableWidgetItem(self.Matix_For_My_Sales[i][j]))
        self.tableWidget_7.clear()
        self.tableWidget_7.setHorizontalHeaderLabels(["Id","Ифнормация","Площадь","Полезная площадь","Наменальная цена","Срок","Покупатель","Предложенная цена"])
        self.Matrix_For_Who_Wont_To_By = self.Estate_main_object.who_want_to_buy()
        if self.Matrix_For_Who_Wont_To_By == []:
            print("Matrix_For_Cam_Be_Slea is Emty")
        else:
            self.tableWidget_7.setRowCount(len(self.Matrix_For_Who_Wont_To_By))
            self.tableWidget_7.setColumnCount(len(self.Matrix_For_Who_Wont_To_By[0]))

            for i in range(len(self.Matrix_For_Who_Wont_To_By)):
                for j in range(len(self.Matrix_For_Who_Wont_To_By[0])):
                    self.tableWidget_7.setItem(i,j,QTableWidgetItem(self.Matrix_For_Who_Wont_To_By[i][j]))
    def update_table_choose(self):
        self.tableWidget_2.clear()
        self.tableWidget_2.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Цена","Срок"])
        self.Matrix_For_Choose_to_by = self.Estate_main_object.choose_to_buy()
        if self.Matrix_For_Choose_to_by ==[]:
            print("Matrix_For_Choose_to_by is Emty") #DEBUG
        else:
            self.tableWidget_2.setRowCount(len(self.Matrix_For_Choose_to_by))
            self.tableWidget_2.setColumnCount(len(self.Matrix_For_Choose_to_by[0]))

            for i in range(len(self.Matrix_For_Choose_to_by)):
                for j in range(len(self.Matrix_For_Choose_to_by[0])):
                    self.tableWidget_2.setItem(i,j,QTableWidgetItem(self.Matrix_For_Choose_to_by[i][j]))
        self.tableWidget_3.clear()
        self.tableWidget_3.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Наминальная цена","Срок","Покупатель","Предложенная цена"])
        self.Matrix_For_I_By = self.Estate_main_object.i_have_payed()
        if self.Matrix_For_I_By==[]:
            print("Matrix_For_I_By is Emty")#DEBUG
        else:
            self.tableWidget_3.setRowCount(len(self.Matrix_For_I_By))
            self.tableWidget_3.setColumnCount(len(self.Matrix_For_I_By[0]))

            for i in range(len(self.Matrix_For_I_By)):
                for j in range(len(self.Matrix_For_I_By)):
                    self.tableWidget_3.setItem(i,j,QTableWidgetItem(self.Matrix_For_I_By[i][j]))
    def zalog_update(self):
        self.tableWidget_4.clear()
        self.tableWidget_4.setHorizontalHeaderLabels(["Id", "Информация", "Площадь", "Полезная площадь"])
        self.Matrix_For_Zalog_My_Sobstvennost = self.Estate_main_object.can_pledge()
        if self.Matrix_For_Zalog_My_Sobstvennost==[]:
            print("Matrix_For_Zalog_My_Sobstvennost is Emty")#DEBUG
        else:
            self.tableWidget_4.setRowCount(len(self.Matrix_For_Zalog_My_Sobstvennost))
            self.tableWidget_4.setColumnCount(len(self.Matrix_For_Zalog_My_Sobstvennost[0]))

            for i in range(len(self.Matrix_For_Zalog_My_Sobstvennost)):
                for j in range(len(self.Matrix_For_Zalog_My_Sobstvennost[0])):
                    self.tableWidget_4.setItem(i,j,QTableWidgetItem(self.Matrix_For_Zalog_My_Sobstvennost[i][j]))
        self.tableWidget_8.clear()
        self.tableWidget_8.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Деньги","Длительность"])
        self.Matrix_For_My_Zalogs = self.Estate_main_object.my_pledges()
        if self.Matrix_For_My_Zalogs==[]:
            print("Matrix_For_My_Zalogs is Emty")#DEBUG
        else:
            self.tableWidget_8.setRowCount(len(self.Matrix_For_My_Zalogs))
            self.tableWidget_8.setColumnCount(len(self.Matrix_For_My_Zalogs[0]))
            for i in range(len(self.Matrix_For_My_Zalogs)):
                for j in range(len(self.Matrix_For_My_Zalogs[0])):
                    self.tableWidget_8.setItem(i,j,QTableWidgetItem(self.Matrix_For_My_Zalogs[i][j]))
        self.tableWidget_9.clear()
        self.tableWidget_9.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Предлогает залог","Деньги","Длительность"])
        self.Matrix_For_Get_Zalog = self.Estate_main_object.show_pledges_i_got()
        if self.Matrix_For_Get_Zalog==[]:
            print("Matrix_For_Get_Zalog is Emty")#DEBUG
        else:
            self.tableWidget_9.setRowCount(len(self.Matrix_For_Get_Zalog))
            self.tableWidget_9.setColumnCount(len(self.Matrix_For_Get_Zalog[0]))

            for i in range(len(self.Matrix_For_Get_Zalog)):
                for j in range(len(self.Matrix_For_Get_Zalog[0])):
                    self.tableWidget_9.setItem(i,j,QTableWidgetItem(self.Matrix_For_Get_Zalog[i][j]))
        self.tableWidget_10.clear()
        self.tableWidget_10.setHorizontalHeaderLabels(["Id","Информация","Площадь","Полезная площадь","Залогодатель", "Сумма","Срок"])
        self.Matrix_For_Getting_For_Me_Zalogs = self.Estate_main_object.show_pledges_when_i_find_money()
        if self.Matrix_For_Getting_For_Me_Zalogs==[]:
            print("Matrix_For_Getting_For_Me_Zalogs is Emty")#DEBUG
        else:
            self.tableWidget_10.setRowCount(len(self.Matrix_For_Getting_For_Me_Zalogs))
            self.tableWidget_10.setColumnCount(len(self.Matrix_For_Getting_For_Me_Zalogs[0]))

            for i in range(len(self.Matrix_For_Getting_For_Me_Zalogs)):
                for j in range(len(self.Matrix_For_Getting_For_Me_Zalogs[0])):
                    self.tableWidget_10.setItem(i,j,QTableWidgetItem(self.Matrix_For_Getting_For_Me_Zalogs[i][j]))
    def update_get_zalog(self):
        self.tableWidget_11.clear()
        self.tableWidget_11.setHorizontalHeaderLabels(["Id","Кому выдать","Площадь","Полезная площадь","Информация","Сумма" ,"Длительность"])
        self.Matrix_For_Gettin_Other_Zalog = self.Estate_main_object.choose_to_guess_pledge()
        if self.Matrix_For_Gettin_Other_Zalog == []:
            print("Matrix_For_Gettin_Other_Zalog is Emty")#DEBUG
        else:
            self.tableWidget_11.setRowCount(len(self.Matrix_For_Gettin_Other_Zalog))
            self.tableWidget_11.setColumnCount(len(self.Matrix_For_Gettin_Other_Zalog[0]))

            for i in range(len(self.Matrix_For_Gettin_Other_Zalog)):
                for j in range(len(self.Matrix_For_Gettin_Other_Zalog[0])):
                    self.tableWidget_11.setItem(i,j,QTableWidgetItem(self.Matrix_For_Gettin_Other_Zalog[i][j]))
        self.tableWidget_12.clear()
        self.tableWidget_12.setHorizontalHeaderLabels(["Id","Кому выдать","Площадь","Полезная площадь","Информация","Сумма" ,"Длительность"])
        self.Matrix_For_Pred_My_Zalogs = self.Estate_main_object.choose_to_cancel_guess_pledge()
        if self.Matrix_For_Pred_My_Zalogs == []:
            print("Matrix_For_Pred_My_Zalogs is Emty")  # DEBUG
        else:
            self.tableWidget_12.setRowCount(len(self.Matrix_For_Pred_My_Zalogs))
            self.tableWidget_12.setColumnCount(len(self.Matrix_For_Pred_My_Zalogs[0]))

            for i in range(len(self.Matrix_For_Pred_My_Zalogs)):
                for j in range(len(self.Matrix_For_Pred_My_Zalogs[0])):
                    self.tableWidget_12.setItem(i, j, QTableWidgetItem(self.Matrix_For_Pred_My_Zalogs[i][j]))
        self.tableWidget_13.clear()
        self.tableWidget_13.setHorizontalHeaderLabels(["Id", "Информация", "Площадь", "Полезная площадь", "Залогодатель", "Сумма", "Срок"])
        self.Matrix_For_Get_My_Zalogs = self.Estate_main_object.choose_to_cancel_guess_pledge()
        if self.Matrix_For_Get_My_Zalogs == []:
            print("Matrix_For_Get_My_Zalogs is Emty")  # DEBUG
        else:
            self.tableWidget_13.setRowCount(len(self.Matrix_For_Get_My_Zalogs))
            self.tableWidget_13.setColumnCount(len(self.Matrix_For_Get_My_Zalogs[0]))

            for i in range(len(self.Matrix_For_Get_My_Zalogs)):
                for j in range(len(self.Matrix_For_Get_My_Zalogs[0])):
                    self.tableWidget_13.setItem(i, j, QTableWidgetItem(self.Matrix_For_Get_My_Zalogs[i][j]))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Моя Собственность"))
        self.update_push_button_1.setText(_translate("Dialog", "Обновить Таблицы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Моя собственность"))
        self.label_2.setText(_translate("Dialog", "Что Можно подарить"))
        self.Presen_push_button.setText(_translate("Dialog", "Подарить"))
        self.label_21.setText(_translate("Dialog", "Время в днях"))
        self.label_22.setText(_translate("Dialog", "Адрес"))
        self.label_3.setText(_translate("Dialog", "Я дарю"))
        self.chansel_present_push_button.setText(_translate("Dialog", "Оменить"))
        self.label_23.setText(_translate("Dialog", "Мне дарят"))
        self.pushButton.setText(_translate("Dialog", "Обновить все таблицы"))
        self.pushButton_20.setText(_translate("Dialog", "Принять"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Подарки"))
        self.label_4.setText(_translate("Dialog", "Выбрать"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.pushButton_2.setText(_translate("Dialog", "Выбрать"))
        self.label_6.setText(_translate("Dialog", "Я покупаю"))
        self.pushButton_3.setText(_translate("Dialog", "Отменить покупку"))
        self.pushButton_5.setText(_translate("Dialog", "Обновить все таблицы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Купля"))
        self.label_8.setText(_translate("Dialog", "Наша собственность"))
        self.label_10.setText(_translate("Dialog", "Время в днях"))
        self.label_9.setText(_translate("Dialog", "Цена"))
        self.pushButton_6.setText(_translate("Dialog", "Продать"))
        self.label_11.setText(_translate("Dialog", "Выберите что бы отменить продажу"))
        self.pushButton_7.setText(_translate("Dialog", "Оменить продажу"))
        self.label_12.setText(_translate("Dialog", "Покупатели"))
        self.pushButton_8.setText(_translate("Dialog", "Продать"))
        self.pushButton_9.setText(_translate("Dialog", "Обновить все таблицы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Продажа"))
        self.label_7.setText(_translate("Dialog", "Моя собственность"))
        self.label_14.setText(_translate("Dialog", "Дни"))
        self.label_13.setText(_translate("Dialog", "Цена"))
        self.pushButton_4.setText(_translate("Dialog", "Заложить"))
        self.label_15.setText(_translate("Dialog", "Мои залоги"))
        self.pushButton_10.setText(_translate("Dialog", "Отменить"))
        self.label_16.setText(_translate("Dialog", "Получить залоги"))
        self.pushButton_12.setText(_translate("Dialog", "Откозать"))
        self.pushButton_11.setText(_translate("Dialog", "Принять"))
        self.label_17.setText(_translate("Dialog", "Выданные мне залоги"))
        self.pushButton_14.setText(_translate("Dialog", "Вернуть"))
        self.pushButton_13.setText(_translate("Dialog", "Обновить все таблицы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Взять под залог"))
        self.label_18.setText(_translate("Dialog", "Выберите что бы выдать залог"))
        self.pushButton_15.setText(_translate("Dialog", "Выдать"))
        self.label_19.setText(_translate("Dialog", "Предложенные мною залоги"))
        self.pushButton_16.setText(_translate("Dialog", "Отменить"))
        self.label_20.setText(_translate("Dialog", "Выданные мною залоги"))
        self.pushButton_17.setText(_translate("Dialog", "Отказать"))
        self.pushButton_18.setText(_translate("Dialog", "Выдать"))
        self.pushButton_19.setText(_translate("Dialog", "Обновить все таблицы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Выдать залог"))
        self.label_24.setText(_translate("Dialog", "Адресс пользователя"))
        self.label_25.setText(_translate("Dialog", "Физический Адресс"))
        self.label_26.setText(_translate("Dialog", "Общая площадь"))
        self.label_27.setText(_translate("Dialog", "Полезная площадь"))
        self.pushButton_21.setText(_translate("Dialog", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Добавление Имущества"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

